name: Tag

on:
  push:
    tags: ['v*']

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - name: Setup PowerShell
      uses: CRFricke/Setup-PowerShell@v1.0.10

    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Build Version
      shell: pwsh
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v9'
      run: |
        Get-VersionVariables
        Set-ActionVariable "BUILD_VERSION" "$Tag_Version"
        Write-Host "BUILD_VERSION: $Tag_Version"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/CRFricke/index.json
        owner: CRFricke
      env:
          NUGET_AUTH_TOKEN: ${{secrets.USER_PAT}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore /p:Version=$BUILD_VERSION

    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal

    - name: Create NuGet package
      run: dotnet pack EF.Core.Utilities.NoTests.slnf --configuration $BUILD_CONFIG --no-build /p:Version=$BUILD_VERSION

    - name: Upload NuGet package to GitHub
      run: dotnet nuget push "**/*.nupkg" --source https://nuget.pkg.github.com/CRFricke/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
